coverage:
  precision: 2
  round: down
  range: 70...100
  status:
    patch:
      default:
        target: 80% # Required patch coverage target
    project:
      default:
        threshold: 0.5%  # Allowable coverage drop in percentage points

comment:
  behavior: default
  require_changes: false
  require_base: false
