enableGlobalCache: true

nodeLinker: node-modules
npmMinimalAgeGate: '3d'
npmPreapprovedPackages:
  - react
  - react-native
  - universal-test-renderer
  - '@testing-library/react-native'
  - '@react-native/*'
  - '@types/react'
  - hermes-compiler

yarnPath: .yarn/releases/yarn-4.11.0.cjs
