enableGlobalCache: true

nodeLinker: node-modules
npmMinimalAgeGate: '1d'
npmPreapprovedPackages:
  - hermes-compiler
  - react
  - react-native
  - test-renderer
  - '@react-native/*'
  - '@types/react'

yarnPath: .yarn/releases/yarn-4.11.0.cjs
