enableGlobalCache: true

nodeLinker: node-modules
npmMinimalAgeGate: '3d'
npmPreapprovedPackages:
 - react
 - react-native
 - react-test-renderer
 - @react-native/*


yarnPath: .yarn/releases/yarn-4.11.0.cjs
