name: Setup deps
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@49933eaac618a4045da5c5ba6b6a05208f4c5f3b # v4.4.0
      with:
        node-version-file: .nvmrc

    - name: Cache deps
      id: yarn-cache
      uses: actions/cache@a3ec84d8ac3925e8ca3ed95ee7e46eed168d7b0e # v4.2.3
      with:
        path: |
          ./node_modules
          .yarn/install-state.gz
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/package.json', '!node_modules/**') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          ${{ runner.os }}-yarn-

    - name: Install deps
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --immutable
      shell: bash
