name: Setup Website deps
description: Setup Node.js and install website dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: .nvmrc

    - name: Cache website deps
      id: yarn-cache-website
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ./website/node_modules
          ./website/yarn/install-state.gz
        key: website-${{ runner.os }}-yarn-${{ hashFiles('./website/yarn.lock') }}

    - name: Install website deps
      if: steps.yarn-cache-website.outputs.cache-hit != 'true'
      run: yarn --cwd website install --immutable
      shell: bash
