name: Setup Website deps
description: Setup Node.js and install website dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.4
      with:
        node-version-file: .nvmrc

    - name: Cache website deps
      id: yarn-cache-website
      uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4.0.1
      with:
        path: |
          ./website/node_modules
          ./website/yarn/install-state.gz
        key: website-${{ runner.os }}-yarn-${{ hashFiles('./website/yarn.lock') }}

    - name: Install website deps
      if: steps.yarn-cache-website.outputs.cache-hit != 'true'
      run: yarn --cwd website install --immutable
      shell: bash
