#!/usr/bin/env bash

cp yarn.lock yarn.lock.backup
cp package.json package.json.backup

yarn add -D react@17.0.2 react-test-renderer@17.0.2 react-native@0.68.3 --ignore-scripts
yarn test:ci --collectCoverage=false

mv package.json.backup package.json
mv yarn.lock.backup yarn.lock

yarn --ignore-scripts
