name: CI
on:
  push:
    branches: [main, v13-stable]
  pull_request:
    branches: ['**']

# Set minimal permissions by default
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'main')}}

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node.js and deps
        uses: ./.github/actions/setup-deps

      - name: Lint
        run: yarn lint

      - name: Prettier
        run: yarn prettier

  typecheck:
    runs-on: ubuntu-latest
    name: Typecheck
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node.js and deps
        uses: ./.github/actions/setup-deps

      - name: Typecheck
        run: yarn typecheck

  typecheck-react-18:
    runs-on: ubuntu-latest
    name: Typecheck React 18
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node.js and deps
        uses: ./.github/actions/setup-deps-react-18

      - name: Typecheck
        run: yarn typecheck

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node.js and deps
        uses: ./.github/actions/setup-deps

      - name: Test
        run: yarn test:ci:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@e53489f4d376d79066609109e7a95a29eb3740b1 # v7.0.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-react-18:
    runs-on: ubuntu-latest
    name: Test React 18
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node.js and deps
        uses: ./.github/actions/setup-deps-react-18

      - name: Test
        run: yarn test:ci
