name: React Native Nightly
on:
  # Runs every night at 5 AM
  schedule:
    - cron: '0 5 * * *'
  # Manaual trigger
  workflow_dispatch:

# Set minimal permissions by default
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'main')}}

jobs:
  install-cache-deps:
    runs-on: ubuntu-latest
    name: Install and Cache deps
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup
        uses: ./.github/actions/setup-deps

  lint:
    needs: [install-cache-deps]
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js and deps
        uses: ./.github/actions/setup-deps-nightly

      - name: Lint
        run: yarn lint

  typecheck:
    needs: [install-cache-deps]
    runs-on: ubuntu-latest
    name: Typecheck
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js and deps
        uses: ./.github/actions/setup-deps-nightly

      - name: Typecheck
        run: yarn typecheck

  test:
    needs: [install-cache-deps]
    runs-on: ubuntu-latest
    name: Test React 18
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js and deps
        uses: ./.github/actions/setup-deps-nightly

      - name: Test
        run: yarn test:ci
